# Form implementation generated from reading ui file 'ui/notes.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 570)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #000000;\n"
"    border: 1px solid #000000;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #393939;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 33px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 390, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #433427;\n"
"    color: #fcfdfb;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 390, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #433427;;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 400, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #202020;;\n"
"    color: #3b7b7b;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 400, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #202020;;\n"
"    color: #3b7b7b;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 400, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #202020;;\n"
"    color: #3b7b7b;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 400, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #202020;;\n"
"    color: #3b7b7b;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 30, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(False)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(50, 30, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(17)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #202020;;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    color: #545354;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 320, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setBold(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #202020;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    color: #545354;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(49, 100, 591, 211))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #202020;;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    color: #545354;\n"
"}\n"
"QTextEdit:placeholder {\n"
"    font-family: Quicksand;\n"
"    font-size: 15px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Note"))
        self.label_3.setText(_translate("MainWindow", "Editing: "))
        self.pushButton_3.setText(_translate("MainWindow", "B"))
        self.pushButton_4.setText(_translate("MainWindow", "U"))
        self.pushButton_5.setText(_translate("MainWindow", "I"))
        self.pushButton_6.setText(_translate("MainWindow", "H2"))
        self.pushButton_8.setText(_translate("MainWindow", "<"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Heading..."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "folder-name..."))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Write here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
