# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 570)
        font = QtGui.QFont()
        font.setFamily("Charter")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #000000;\n"
"    border: 1px solid #000000;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #393939;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 33px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(60, 30, 290, 91))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setPointSize(48)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #433427;;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 5px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 160, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #433427;\n"
"    color: #fcfdfb;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 230, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Hiragino Maru Gothic ProN")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #433427;\n"
"    color: #fcfdfb;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(27)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #433427;;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 15px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 320, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(27)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #433427;\n"
"    color: #fcfdfb;\n"
"    border: 1px solid #636363;\n"
"    border-radius: 10px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 30, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Marker Felt")
        font.setPointSize(23)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 389, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Mukta Mahee")
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color: #3b7b7b;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.pushButton.setText(_translate("MainWindow", "Light Mode"))
        self.pushButton_2.setText(_translate("MainWindow", "Dark Mode"))
        self.label_3.setText(_translate("MainWindow", "Change Theme:"))
        self.pushButton_3.setText(_translate("MainWindow", "SignOut"))
        self.pushButton_4.setText(_translate("MainWindow", "<"))
        self.pushButton_5.setText(_translate("MainWindow", "delete account? "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
